name: mprime
version: 'git'
summary: Free Mersenne Prime Search Software
description: |
  Prime95 has been a popular choice for stress / torture testing a CPU since its introduction, especially with overclockers and system builders. 

grade: stable
confinement: devmode

architectures:
- build-on: amd64

apps:
  mprime:
    command: $SNAP/mprime
    plugs:
      - network
      - home
      - system-observe
      
parts:
  launcher:
    plugin: dump
    source: script
    stage-packages:
      - wget

    
