name: mprime
version: git
summary: Free Mersenne Prime Search Software (Prime95)
description: |
  Prime95 has been a popular choice for stress / torture testing a CPU since its introduction, especially with overclockers and system builders. Since the software makes heavy use of the processor's integer and floating point instructions, it feeds the processor a consistent and verifiable workload to test the stability of the CPU and the L1/L2/L3 processor cache. Additionally, it uses all of the cores of a multi-CPU / multi-core system to ensure a high-load stress test environment.
grade: stable
confinement: devmode

apps:
  mprime:
    command: $SNAP/mprime
    plugs:
      - network
      - home
      - system-observe
      
parts:
  launcher:
    plugin: dump
    source: script
    stage-packages:
      - wget

    
